function frames = get_interval_frame(M, start_ts, end_ts, unit)
%GET_INTERVAL_FRAME Get frame images from a Movie object for a given time interval.
% frames = get_interval_frame(M, start, end, unit) reads multiple image 
% frames from a given video object M. The frames are extracted from 
% start timestamp STRART_TS to end timestamp END_TS in millisecond. 
% UNIT describes how many units are generated by dividing one second window.
%
% @autor	Jin-Hwa Kim (jhkim@bi.snu.ac.kr)
% @date     2014-06-16

DEBUG = false;
FrameRate = M.FrameRate;
SecondUnit = 1000;

startFrame = start_ts * FrameRate / SecondUnit;
endFrame = end_ts * FrameRate / SecondUnit;
% round() means ending frame is possibly over end_ts.
frameNo = round((endFrame - startFrame)/(FrameRate/unit)) + 1;

frames = uint8(zeros(M.Height, M.Width, 3, frameNo));

for i = 1 : frameNo
    curframe = round(startFrame + (i-1)*(FrameRate/unit));
    frames(:,:,:,i) = uint8(read(M, curframe));
    if DEBUG
        Col = ceil(sqrt(frameNo));
        Row = floor(sqrt(frameNo));
        subplot(Col, Row, i);
        imshow(frames(:,:,:,i));
    end
end