function [descriptor] = pb_descriptor_Datum()
%pb_descriptor_Datum Returns the descriptor for message Datum.
%   function [descriptor] = pb_descriptor_Datum()
%
%   See also pb_read_Datum
  
  descriptor = struct( ...
    'name', 'Datum', ...
    'full_name', 'Datum', ...
    'filename', 'datum.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'channels', ...
        'full_name', 'Datum.channels', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(5), ...
        'matlab_type', uint32(1), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', int32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'int32')), ...
        'write_function', @(x) typecast(int32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'height', ...
        'full_name', 'Datum.height', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(5), ...
        'matlab_type', uint32(1), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', int32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'int32')), ...
        'write_function', @(x) typecast(int32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'width', ...
        'full_name', 'Datum.width', ...
        'index', 3, ...
        'number', uint32(3), ...
        'type', uint32(5), ...
        'matlab_type', uint32(1), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', int32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'int32')), ...
        'write_function', @(x) typecast(int32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'data', ...
        'full_name', 'Datum.data', ...
        'index', 4, ...
        'number', uint32(4), ...
        'type', uint32(12), ...
        'matlab_type', uint32(8), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', uint8(''), ...
        'read_function', @(x) uint8(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'label', ...
        'full_name', 'Datum.label', ...
        'index', 5, ...
        'number', uint32(5), ...
        'type', uint32(5), ...
        'matlab_type', uint32(1), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', int32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'int32')), ...
        'write_function', @(x) typecast(int32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'float_data', ...
        'full_name', 'Datum.float_data', ...
        'index', 6, ...
        'number', uint32(6), ...
        'type', uint32(2), ...
        'matlab_type', uint32(6), ...
        'wire_type', uint32(5), ...
        'label', uint32(3), ...
        'default_value', single([]), ...
        'read_function', @(x) typecast(x, 'single'), ...
        'write_function', @(x) typecast(single(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );
  
  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);
  put(descriptor.field_indeces_by_number, uint32(3), 3);
  put(descriptor.field_indeces_by_number, uint32(4), 4);
  put(descriptor.field_indeces_by_number, uint32(5), 5);
  put(descriptor.field_indeces_by_number, uint32(6), 6);
  
